LogLevel warn
PageLogFormat
MaxLogSize 0
Listen /run/cups/cups.sock
Listen 0.0.0.0:631
Browsing Off
DefaultAuthType None
WebInterface Yes
ServerAlias *

<Location />
  Order allow,deny
  Allow all
</Location>

<Location /admin>
  Order allow,deny
  Allow all
</Location>

<Location /admin/conf>
  Order allow,deny
  Allow all
</Location>

<Policy default>
  JobPrivateAccess default
  JobPrivateValues default
  SubscriptionPrivateAccess default
  SubscriptionPrivateValues default

  <Limit All>
    Order deny,allow
    Allow all
  </Limit>
</Policy>
